repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.1.0
    hooks:
    -   id: trailing-whitespace
        language_version: python3
    -   id: end-of-file-fixer
        files: ^tf|-|\.(py|env|yml|yaml|pem|key|mock)$
    -   id: detect-private-key
        files: ^(?!\.?git-crypt)
        exclude: ^docker/templates/id_rsa$
    -   id: check-merge-conflict
        files: ^tf|-|\.(py|tfvars|tf|tfenv|env|yml|yaml|pem|key|mock)$
    -   id: check-added-large-files
        files: ^tf|-|\.(py|env|yml|yaml)$
    -   id: check-case-conflict
    -   id: check-json
        language_version: python3
    -   id: check-xml
        language_version: python3
    -   id: check-yaml
        language_version: python3
    -   id: check-case-conflict
    -   id: check-ast
        language_version: python3
    -   id: double-quote-string-fixer
    -   id: check-docstring-first
    -   id: pretty-format-json
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: name-tests-test
    -   id: file-contents-sorter
    -   id: fix-encoding-pragma
    -   id: sort-simple-yaml
-   repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.7.3
    hooks:
    -   id: flake8
        files: ^src/.*\.py$
        args:
        - --max-line-length=80
        - --diff
        - --exclude=docs,migrations
-   repo: https://github.com/pre-commit/mirrors-pylint.git
    rev: v2.5.3
    hooks:
    -   id: pylint
        language_version: python3
        exclude: ^migrations/.*\.py$
        args:
        - --rcfile=.pylintrc
        - --errors-only
        - --disable=no-name-in-module,import-error
        - --ignore=settings_test, migrations
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.3
    hooks:
    -   id: python-safety-dependencies-check
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    -   id: bandit
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.3
    hooks:
    -   id: autopep8
        args:
        - -i
        - --ignore=E501
        language_version: python3
